### ISSUE TITLE
max crashed when import hka anim with v1.12

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/HavokMax#20]
**Describe the bug**
import hkx skeleton with no problem
max crashed( frozen ) when import hka anim with "_add" subfx
import hka with no problem if NOT with "_add" subfx

**File information**
[https://drive.google.com/file/d/1568PU-0V7srRTsugP45UPNcRqM6MI0SV/view?usp=sharing](url)

**3DS Max version**
3DS Max 2016 x64

**Plugin version**
v1.12

**Comment by PredatorCZ** [comment]
HCT shows some weird corrupted animations.

**Comment by redtankbai** [comment]
same animation can be import with no problem by havokmax v1.10, with same 3dsmax 2016 x64
just confirmed and FYI

the reason i need it work with 1.12 is for root motion

**Comment by PredatorCZ** [comment]
Issue will be fixed in next release.
For some reason those animations are not marked as additive, you will need to change `blendHint` value to `ADDITIVE` inside Animation Binding class.
Or if you'll convert them into tagfile (for HCT, it's the only way to convert them into XML), you'll need to add `<int name="blendHint">2</int>` param into `hkaAnimationBinding` object.
Otherwise they won't work, at all.

**Comment by redtankbai** [comment]
i believe your idea suppsed to solve the issue, but could you explain a bit that why same additive anim can work with 1.10? just curious

**Comment by PredatorCZ** [comment]
No reason whatsoever, it's caused by floating point quantization error, it's completely random. V1.10 could use more precise float arithmetic, who knows.

**Comment by redtankbai** [comment]
so any chance to pubilish this fix?

**Comment by redtankbai** [comment]
hi, just want to know when you think we can have a fix of this issue? thx!

**Comment by PredatorCZ** [comment]
v1.13, should work, added additive override, gonna need it

**Comment by redtankbai** [comment]
it works, thank you!
